Implement transport logic
inmydelorean/transport pull request #1
Opened 2021-08-17 17:21 UTC by inmydelorean

Все завдання виконано одним комітом. Не було достатнього розуміння необхідної роботи, щоб розбити її на логічні частини.

Залишилось ще багато запитань. Наприклад:

- що потрібно було додавати в масив;
- як краще реалізувати метод пошуку кращого транспорту;
- чому стосовно `initialize` в класі `Car` IDE каже, що не потрібен аргумент `license_number`;
- як правильно використовувати `Comparable`.

2021-08-19 14:54 UTC, averevkin commented
1) у массив треба додати екземпляри классів Bike та Car і це буде одна з інстанс змінних вашого DeliveryService
2) Логіка вашого методу коректна, але треба шукати серед доступних транспортних засобів. У виконавчій частині умови можно просто робити обраний транспорт не доступним
3) У вас помилка у конструкторі для Car. Ви змінюєте семантику конструктора і передаєте запість Hash String. Це можливо в рубі але це може призвести до помилок при виконнанні. Наприклад я не впевнений що super в конструкторі відпрацює як треба. Також це порушення одного з SOLID принципів: Liskov substitution. Більше про SOLID тут:
https://www.honeybadger.io/blog/ruby-solid-design-principles/
4) Ви правильно додали Comperable, але я б хотів щоб в реалызації <=> ви не використовували <=>

2021-08-19 14:54 UTC, averevkin commented
І чекаю доповнення ПР з тестами.

2021-08-20 07:36 UTC, averevkin commented
Перепрошую, трохи заплутався в ДЗ. Тести для цього завдання не обовв'язкові. Це буде наступне завдання

2021-08-23 09:37 UTC, averevkin requested changes

2021-08-23 09:37 UTC, averevkin commented on transport.rb
> +    @speed = opts[:speed]
max_weight та speed у вас використовуються як знаменники при обчисленнях. Треба додати перевірку атрибутів, що ми не можемо створити інстанс класу Transport з 0. Зробіть 2 додаткових методи(process_speed та process_weight) які будуть перевіряти чи значення 0 і якщо так - рейзити ексепшин, якщо ні - повертати значення.

2021-08-23 09:37 UTC, averevkin commented on transport.rb
> +end
No empty line

2021-08-23 09:37 UTC, averevkin commented on delivery_service.rb
> +    @available_cars_number = CARS_NUMBER
У делівері сервісу має бути інстанс змінна з массивом транспорту цього сервісу. available_cars_number та available_bikes_number не потрібні

2021-08-23 09:37 UTC, averevkin commented on car.rb
> +    super
Коли ви викликаєте super без аргументів, то туди форвардяться усі аргументи в виклику, тобто ваш транспорт отримає license_number

2021-08-23 09:37 UTC, averevkin commented on car.rb
> +    super
Також виклик super повинен бути зверху, тому що коли ви викликаєте його знизу, то він перепише max_weight та speed

2021-08-23 09:37 UTC, averevkin commented on car.rb
> +  def initialize(license_number)
Сігнатура конструктора нащадка повинна співпадати з сігнатурою предка, тобто якщо предок працює з Hash то і нащадок теж повинен отримувати Hash

2021-08-23 09:37 UTC, averevkin commented on transport.rb
> +    @max_weight = opts[:max_weight]
Якщо ви використовуєте double splat оператор то краще використовувати fetch замість прямого доступу, по fetch поверне помилку якщо цього аргументу нема, а прямий доступ поверне nil

2021-08-23 09:37 UTC, averevkin commented on transport.rb
> +    delivery_efficiency <=> other.delivery_efficiency
Це не помилка використовувати <=>, але в завданні хотілось би побачити рішення без використання <=>. Це потрібно для розуміння як цей оператор працює під капотом

2021-08-23 09:37 UTC, averevkin commented on bike.rb
> +    super
Тут super викличеться з nil у аргументах.

2021-08-23 22:29 UTC, inmydelorean commented
@averevkin Дякую за детальний фідбек. Намагаюсь пофіксити, але поки що деякі моменти не дуже зрозумілі, не тому що погано пояснили, просто знань по темі не вистачає. Та й приклади у книжках і інших ресурсах досить тривіальні, немає point of reference. Буду розбиратись далі, напишу вам якщо не розберусь.

2021-08-25 14:30 UTC, inmydelorean commented on bike.rb
> +    super
Виправив.

2021-08-25 14:32 UTC, inmydelorean commented on car.rb
> +  def initialize(license_number)
Дякую, не знав цього. Виправив суперклас, щоб все було однаково.

2021-08-25 14:33 UTC, inmydelorean commented on car.rb
> +    super
Виправив.

2021-08-25 14:35 UTC, inmydelorean commented on delivery_service.rb
> +    @available_cars_number = CARS_NUMBER
Майже зрозумів що потрібно робити. Наступний коміт це частково пофіксить.

2021-08-25 14:39 UTC, inmydelorean commented on transport.rb
> +    @max_weight = opts[:max_weight]
Замінив double splat оператор звичайними аргументами. Треба розібратись із базовими моментами, перед тим як переходити до більш складних.

2021-08-25 14:40 UTC, inmydelorean commented on transport.rb
> +    @speed = opts[:speed]
Зрозумів, дякую.

2021-08-25 14:42 UTC, inmydelorean commented on transport.rb
> +    delivery_efficiency <=> other.delivery_efficiency
Я розумію завдання, але всі ресурси дають Comparable саме з ним. Буду далі розбиратись в цій темі.

2021-08-25 15:05 UTC, inmydelorean commented
@averevkin Щось із того, на що ви вказали я пофіксив (мені так здається). Пару моментів ще не повністю зрозумів.

1. Comparable у всіх статтях і доках показують через `<=>`. Я розумію, що ви хочете, просто не знаю як це оформити. Цей приклад схожий на те, чого ви очікуєте?
`1 if self>other; 0 if self==other; -1 if self<other`

2. Стосовно масиву з усім транспортом. Велосипеди я додав таким чином:
`@available_transport = Array.new(Constants::BIKES_NUMBER) { Bike.new }`
Чи можна якось створити масив з двома класами, при цьому нам потрібно різна кількість інстансів кожного? Плюс нам ще потрібно згенерувати (чи підтягнути готові) реєстраційні номери для машин. Поки що не знайшов, як це зробити.

2021-08-25 15:09 UTC, averevkin commented on car.rb
> +    super(max_weight, speed)
Передавайте одразу тут CAR_MAX_WEIGHT та CAR_MAX_SPEED

2021-08-25 15:11 UTC, averevkin commented on bike.rb
> +    super(max_weight, speed)
Передавайте одразу тут BIKE_MAX_WEIGHT та BIKE_MAX_SPEED

2021-08-25 15:11 UTC, averevkin commented on delivery_service.rb
> +  def initialize(weight, distance)
weight та distance повинні бути аргументами вашого find_transport методу. У поточній реалізаціі вам потрібно буде створювати окремий DeliveryService для кожної посилки

2021-08-25 15:15 UTC, averevkin commented
@inmydelorean 
1) Так дуже схоже. Рекомендую використовувати if ... elsif ... else конструкцію
2) Щоб було простіше, можете генерувати license_number за допомогою rand(1000..9999). щодо массиву який рандомно створює массив з транспортом, я би не ускладнював і просто зробив би окремо available_bikes та available_cars, а потім просто їх приєднав

2021-08-30 08:26 UTC, averevkin approved these changes

2021-08-30 08:26 UTC, averevkin commented on transport.rb
> +  def compare_transport(other)
Сравнение должно быть сделано относительно delivery_efficiency каждого транспорта

2021-08-30 08:26 UTC, averevkin commented on delivery_service.rb
> +      element.available == true && weight <= element.max_weight && distance <= element.max_distance if element.max_distance.present?
1) Если max_distance.present? false то тут будет nil соответственно транспорт типа Car никогда не будет выбран
2) Сравнение с element.available == true некорректно потому что element.available == true  и element.available имеют ту же самую таблицу соответствия
3) у Car нет метода max_distance, значит будет ошибка при вызове, используйте safe navigation element&.max_distance

2021-09-05 21:56 UTC, merged

2021-09-06 20:28 UTC, inmydelorean commented on transport.rb
> +  def compare_transport(other)
Тобто нам потрібно переписати метод delivery_efficiency і видалити з нього @speed? Я не бачу сенсу в delivery_efficiency, якщо ми будемо брати до уваги лише @max_weight і max_distance.